begin;

create table if not exists iluminate.render_artifacts (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete cascade,
  bundle_hash text not null,
  profile text not null,
  status text not null default 'pending',
  privacy text not null default 'private',
  bundle_object_key text not null,
  video_object_key text,
  poster_object_key text,
  video_checksum text,
  poster_checksum text,
  width integer,
  height integer,
  duration_ms integer,
  error_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint render_artifacts_bundle_hash_ck check (bundle_hash ~ '^sha256:[0-9a-f]{64}$'),
  constraint render_artifacts_status_ck check (status in ('pending', 'rendering', 'ready', 'failed', 'cancelled')),
  constraint render_artifacts_privacy_ck check (privacy in ('private', 'review', 'unlisted', 'public')),
  constraint render_artifacts_dimensions_ck check ((width is null and height is null) or (width > 0 and height > 0)),
  constraint render_artifacts_duration_ck check (duration_ms is null or duration_ms > 0),
  unique (client_id, bundle_hash, profile, privacy)
);

create table if not exists iluminate.render_jobs (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete cascade,
  artifact_id bigint not null references iluminate.render_artifacts(id) on delete cascade,
  bundle_hash text not null,
  profile text not null,
  status text not null default 'queued',
  attempts integer not null default 0,
  lease_owner text,
  lease_expires_at timestamptz,
  error_summary text,
  available_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint render_jobs_bundle_hash_ck check (bundle_hash ~ '^sha256:[0-9a-f]{64}$'),
  constraint render_jobs_status_ck check (status in ('queued', 'running', 'complete', 'failed', 'cancelled')),
  constraint render_jobs_attempts_ck check (attempts >= 0)
);

create unique index if not exists render_jobs_one_active_idx
  on iluminate.render_jobs (client_id, artifact_id)
  where status in ('queued', 'running');

create index if not exists render_jobs_claim_idx
  on iluminate.render_jobs (available_at, created_at)
  where status = 'queued';

create table if not exists iluminate.scene_shares (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete cascade,
  partitura_id bigint not null references iluminate.partituras(id) on delete cascade,
  artifact_id bigint not null references iluminate.render_artifacts(id) on delete restrict,
  opaque_slug text not null unique,
  access_policy text not null default 'private',
  password_hash text,
  expires_at timestamptz,
  revoked_at timestamptz,
  created_by bigint references public.auth_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint scene_shares_policy_ck check (access_policy in ('private', 'review', 'unlisted', 'public')),
  constraint scene_shares_expiry_ck check (expires_at is null or expires_at > created_at)
);

create index if not exists scene_shares_tenant_idx on iluminate.scene_shares (client_id, created_at desc);
create index if not exists scene_shares_partitura_idx on iluminate.scene_shares (partitura_id, created_at desc);

create table if not exists iluminate.publication_audit (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete cascade,
  actor_id bigint references public.auth_users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  from_policy text,
  to_policy text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint publication_audit_policy_ck check (
    (from_policy is null or from_policy in ('private', 'review', 'unlisted', 'public'))
    and (to_policy is null or to_policy in ('private', 'review', 'unlisted', 'public'))
  )
);

create index if not exists publication_audit_tenant_idx on iluminate.publication_audit (client_id, created_at desc);

commit;
