begin;

create schema if not exists iluminate;

create table if not exists iluminate.partituras (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete restrict,
  project_id bigint not null references iluminate.projects(id) on delete cascade,
  partitura_key text not null,
  name text not null,
  status text not null default 'draft',
  document_json jsonb not null,
  generated_json jsonb,
  validation_report jsonb not null default '{}'::jsonb,
  created_by_user_id bigint references public.auth_users(id) on delete set null,
  updated_by_user_id bigint references public.auth_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint iluminate_partituras_status_ck check (status in ('draft', 'validated', 'active', 'archived')),
  constraint iluminate_partituras_key_ck check (partitura_key ~ '^[a-zA-Z0-9][a-zA-Z0-9_.:-]*$'),
  constraint iluminate_partituras_name_ck check (length(btrim(name)) > 0),
  constraint iluminate_partituras_document_object_ck check (jsonb_typeof(document_json) = 'object'),
  constraint iluminate_partituras_generated_object_ck check (generated_json is null or jsonb_typeof(generated_json) = 'object'),
  constraint iluminate_partituras_validation_object_ck check (jsonb_typeof(validation_report) = 'object'),
  constraint iluminate_partituras_project_uk unique (project_id),
  constraint iluminate_partituras_client_key_uk unique (client_id, partitura_key)
);

create index if not exists iluminate_partituras_client_status_idx
  on iluminate.partituras (client_id, status, updated_at desc)
  where deleted_at is null;

create index if not exists iluminate_partituras_document_gin_idx
  on iluminate.partituras using gin (document_json);

comment on table iluminate.partituras is
  'Current editable partitura for a client project. Iluminate does not model partitura revisions; variants are separate partitura records.';

comment on column iluminate.partituras.document_json is
  'Editable designer document used by the web workspace: strings, segments, zones, scenes, clips and simulator defaults.';

comment on column iluminate.partituras.generated_json is
  'Last validated partitura JSON artifact generated from document_json for simulator/firmware consumption. It must not include revision numbers.';

commit;
