begin;

create schema if not exists iluminate;

create table if not exists iluminate.projects (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete restrict,
  name text not null,
  description text not null default '',
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint iluminate_projects_status_ck check (status in ('draft', 'active', 'archived')),
  constraint iluminate_projects_name_ck check (length(btrim(name)) > 0)
);

create table if not exists iluminate.controllers (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete restrict,
  project_id bigint references iluminate.projects(id) on delete set null,
  controller_key text not null,
  name text not null,
  status text not null default 'provisioning',
  last_seen_at timestamptz,
  firmware_version text,
  active_partitura_id bigint,
  desired_partitura_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint iluminate_controllers_status_ck check (status in ('provisioning', 'active', 'inactive', 'maintenance', 'retired')),
  constraint iluminate_controllers_key_ck check (controller_key ~ '^[a-zA-Z0-9][a-zA-Z0-9_.:-]*$'),
  constraint iluminate_controllers_name_ck check (length(btrim(name)) > 0),
  constraint iluminate_controllers_key_uk unique (controller_key)
);

create table if not exists iluminate.deployments (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete restrict,
  project_id bigint not null references iluminate.projects(id) on delete cascade,
  controller_id bigint not null references iluminate.controllers(id) on delete cascade,
  partitura_id bigint,
  status text not null default 'pending',
  requested_by_user_id bigint references public.auth_users(id) on delete set null,
  requested_at timestamptz not null default now(),
  downloaded_at timestamptz,
  applied_at timestamptz,
  failed_at timestamptz,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  constraint iluminate_deployments_status_ck check (status in ('pending', 'downloaded', 'applied', 'failed', 'rolled_back', 'cancelled')),
  constraint iluminate_deployments_metadata_object_ck check (jsonb_typeof(metadata) = 'object')
);

create table if not exists iluminate.device_commands (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete restrict,
  controller_id bigint not null references iluminate.controllers(id) on delete cascade,
  command_type text not null,
  command_sequence integer not null,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  created_by_user_id bigint references public.auth_users(id) on delete set null,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  error_message text,
  constraint iluminate_device_commands_type_ck check (command_type in ('set_scene', 'refresh_partitura', 'rollback', 'restart', 'identify')),
  constraint iluminate_device_commands_status_ck check (status in ('pending', 'sent', 'processed', 'failed', 'cancelled')),
  constraint iluminate_device_commands_sequence_ck check (command_sequence > 0),
  constraint iluminate_device_commands_payload_object_ck check (jsonb_typeof(payload) = 'object'),
  constraint iluminate_device_commands_controller_sequence_uk unique (controller_id, command_sequence)
);

create table if not exists iluminate.device_status_reports (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete restrict,
  controller_id bigint not null references iluminate.controllers(id) on delete cascade,
  reported_partitura_id bigint,
  reported_scene_id text,
  reported_command_sequence integer,
  firmware_version text,
  status text not null default 'online',
  ip_address inet,
  payload jsonb not null default '{}'::jsonb,
  reported_at timestamptz not null default now(),
  constraint iluminate_device_status_reports_status_ck check (status in ('online', 'offline', 'error', 'maintenance')),
  constraint iluminate_device_status_reports_payload_object_ck check (jsonb_typeof(payload) = 'object')
);

create table if not exists iluminate.assets (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.auth_clients(id) on delete restrict,
  project_id bigint references iluminate.projects(id) on delete cascade,
  asset_type text not null,
  storage_uri text not null,
  file_name text not null,
  mime_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by_user_id bigint references public.auth_users(id) on delete set null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint iluminate_assets_type_ck check (asset_type in ('photo', 'render', 'plan', 'svg', 'reference', 'other')),
  constraint iluminate_assets_metadata_object_ck check (jsonb_typeof(metadata) = 'object')
);

create table if not exists iluminate.audit_events (
  id bigint generated by default as identity primary key,
  client_id bigint references public.auth_clients(id) on delete set null,
  actor_user_id bigint references public.auth_users(id) on delete set null,
  entity_type text not null,
  entity_id text,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint iluminate_audit_events_metadata_object_ck check (jsonb_typeof(metadata) = 'object')
);

create index if not exists iluminate_projects_client_status_idx
  on iluminate.projects (client_id, status)
  where deleted_at is null;

create index if not exists iluminate_controllers_client_project_idx
  on iluminate.controllers (client_id, project_id, status)
  where deleted_at is null;

create index if not exists iluminate_deployments_controller_status_idx
  on iluminate.deployments (client_id, controller_id, status, requested_at desc);

create index if not exists iluminate_device_commands_controller_status_idx
  on iluminate.device_commands (client_id, controller_id, status, command_sequence desc);

create index if not exists iluminate_device_status_reports_controller_time_idx
  on iluminate.device_status_reports (client_id, controller_id, reported_at desc);

create index if not exists iluminate_assets_project_idx
  on iluminate.assets (client_id, project_id, asset_type)
  where deleted_at is null;

create index if not exists iluminate_audit_events_client_time_idx
  on iluminate.audit_events (client_id, created_at desc);

comment on schema iluminate is
  'Iluminate operational schema: projects, controllers, partituras, deployments, device state, assets and audit.';

comment on table iluminate.projects is
  'Client-owned LED signage or installation project. A project owns one current persisted partitura.';

comment on table iluminate.controllers is
  'ESP32 controller registry. Controllers receive desired partituras and report status.';

comment on table iluminate.deployments is
  'Publication history linking a current partitura to a target controller.';

comment on table iluminate.device_commands is
  'Commands queued for controllers, such as scene changes, refresh, rollback, restart or identify.';

comment on table iluminate.device_status_reports is
  'Status reports received from controllers, including applied partitura, active scene and health payload.';

comment on table iluminate.assets is
  'Project files used by the editor, such as photos, renders, plans, SVGs and references.';

comment on table iluminate.audit_events is
  'Append-only operational audit trail for important auth, project, partitura and deployment events.';

commit;
