create table if not exists public.auth_password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.auth_users(id) on delete cascade,
  delivery_email text not null,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz
);

create index if not exists auth_password_reset_tokens_user_idx
  on public.auth_password_reset_tokens(user_id, created_at desc);

create index if not exists auth_password_reset_tokens_active_idx
  on public.auth_password_reset_tokens(token_hash, expires_at)
  where used_at is null;
