-- Iluminate auth/security baseline.
-- Idempotent by design: safe to run repeatedly in phase 0 environments.

create table if not exists public.auth_clients (
  id bigint generated by default as identity primary key,
  client_key text not null unique,
  name text not null,
  market text not null default 'CR',
  mode text not null default 'customer',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auth_clients_status_ck check (status in ('active', 'inactive')),
  constraint auth_clients_mode_ck check (mode in ('customer', 'internal', 'demo'))
);

create table if not exists public.auth_roles (
  id text primary key,
  label text not null,
  scope text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  constraint auth_roles_scope_ck check (scope in ('system', 'client'))
);

create table if not exists public.auth_permissions (
  id text primary key,
  label text not null,
  description text not null default ''
);

create table if not exists public.auth_role_permissions (
  role_id text not null references public.auth_roles(id) on delete cascade,
  permission_id text not null references public.auth_permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

create table if not exists public.auth_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text not null unique,
  display_name text not null,
  password_hash text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auth_users_status_ck check (status in ('active', 'inactive', 'locked'))
);

create table if not exists public.auth_user_roles (
  user_id bigint not null references public.auth_users(id) on delete cascade,
  role_id text not null references public.auth_roles(id) on delete restrict,
  primary key (user_id, role_id)
);

create table if not exists public.auth_user_clients (
  user_id bigint not null references public.auth_users(id) on delete cascade,
  client_id bigint not null references public.auth_clients(id) on delete cascade,
  is_default boolean not null default false,
  primary key (user_id, client_id)
);

create table if not exists public.auth_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.auth_users(id) on delete cascade,
  session_token_hash text not null unique,
  active_client_id text,
  active_role_id text references public.auth_roles(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

alter table public.auth_sessions
  add column if not exists active_role_id text references public.auth_roles(id) on delete set null;

create table if not exists public.auth_audit_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.auth_users(id) on delete set null,
  client_id bigint references public.auth_clients(id) on delete set null,
  action text not null,
  subject_type text not null,
  subject_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists auth_sessions_token_hash_idx on public.auth_sessions(session_token_hash);
create index if not exists auth_sessions_user_active_idx on public.auth_sessions(user_id, expires_at) where revoked_at is null;
create index if not exists auth_user_clients_client_idx on public.auth_user_clients(client_id);
create index if not exists auth_audit_log_created_idx on public.auth_audit_log(created_at desc);

insert into public.auth_clients (id, client_key, name, market, mode, status)
values (1, 'iluminate', 'Iluminate', 'CR', 'internal', 'active')
on conflict (id) do update set
  client_key = excluded.client_key,
  name = excluded.name,
  market = excluded.market,
  mode = excluded.mode,
  status = excluded.status,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.auth_clients', 'id'),
  greatest((select coalesce(max(id), 1) from public.auth_clients), 1)
);

insert into public.auth_roles (id, label, scope, description)
values
  ('system-admin', 'Administrador del sistema', 'system', 'Control total de configuracion, seguridad y datos del portal.'),
  ('system-user', 'Operador del sistema', 'system', 'Operacion interna sin administracion completa de seguridad.'),
  ('client-admin', 'Administrador del cliente', 'client', 'Administra usuarios y configuracion dentro de su cliente.'),
  ('client-viewer', 'Usuario del cliente', 'client', 'Consulta datos, senales y evidencia de su cliente.')
on conflict (id) do update set
  label = excluded.label,
  scope = excluded.scope,
  description = excluded.description;

insert into public.auth_permissions (id, label, description)
values
  ('auth:users:manage', 'Administrar usuarios', 'Crear, editar y desactivar usuarios.'),
  ('auth:roles:manage', 'Administrar roles', 'Ver y mantener roles y permisos.'),
  ('auth:clients:manage', 'Administrar clientes', 'Ver y mantener clientes/tenants.'),
  ('lighting:projects:read', 'Leer proyectos', 'Consultar proyectos y rotulos.'),
  ('lighting:projects:manage', 'Administrar proyectos', 'Crear y editar proyectos LED.'),
  ('lighting:partituras:read', 'Leer partituras', 'Consultar revisiones de partitura.'),
  ('lighting:partituras:manage', 'Administrar partituras', 'Crear, validar y versionar partituras.'),
  ('lighting:deployments:manage', 'Administrar despliegues', 'Publicar partituras y cambios de escena.'),
  ('device:controllers:read', 'Leer controladores', 'Consultar controladores ESP32.'),
  ('device:controllers:manage', 'Administrar controladores', 'Registrar y mantener controladores ESP32.'),
  ('audit:events:read', 'Leer auditoria', 'Consultar eventos de auditoria.')
on conflict (id) do update set
  label = excluded.label,
  description = excluded.description;

insert into public.auth_role_permissions (role_id, permission_id)
select 'system-admin', id from public.auth_permissions
on conflict do nothing;

insert into public.auth_role_permissions (role_id, permission_id)
values
  ('system-user', 'lighting:projects:read'),
  ('system-user', 'lighting:partituras:read'),
  ('system-user', 'device:controllers:read'),
  ('system-user', 'audit:events:read'),
  ('client-admin', 'auth:users:manage'),
  ('client-admin', 'lighting:projects:read'),
  ('client-admin', 'lighting:projects:manage'),
  ('client-admin', 'lighting:partituras:read'),
  ('client-admin', 'lighting:partituras:manage'),
  ('client-admin', 'lighting:deployments:manage'),
  ('client-admin', 'device:controllers:read'),
  ('client-admin', 'device:controllers:manage'),
  ('client-viewer', 'lighting:projects:read'),
  ('client-viewer', 'lighting:partituras:read'),
  ('client-viewer', 'device:controllers:read')
on conflict do nothing;

insert into public.auth_users (id, username, email, display_name, password_hash, status)
values (
  1,
  'acartin',
  'acartin@iluminate.local',
  'acartin',
  'pbkdf2_sha256$260000$vAcIV06me30AYkDZlvwP812f$nI3w1F5oUSHkKxNcVkb6UNlHDhtV4Vw7UpgoYKdCO1A',
  'active'
)
on conflict (id) do update set
  username = excluded.username,
  email = excluded.email,
  display_name = excluded.display_name,
  password_hash = excluded.password_hash,
  status = excluded.status,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.auth_users', 'id'),
  greatest((select coalesce(max(id), 1) from public.auth_users), 1)
);

insert into public.auth_user_roles (user_id, role_id)
values (1, 'system-admin')
on conflict do nothing;

insert into public.auth_user_clients (user_id, client_id, is_default)
values (1, 1, true)
on conflict (user_id, client_id) do update set is_default = excluded.is_default;
